//
// Copyright 2004 Jason Lewis
//

package net.nexttext.input;

import java.awt.Component;

import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;

/**
 * An interface for the keyboard.
 *
 * <p>The {@link KeyEvent} objects generated by the Java {@link KeyListener} 
 * are wrapped into {@link KeyboardEvent} objects and added to the event 
 * list.  This keyboard input source does not keep the current state of the 
 * keys, but it could be done by adding a list of key that are being pressed.
 * </p>
 */

public class KeyboardDefault extends Keyboard implements KeyListener {

    static final String REVISION = "$CVSHeader: obx/NextText/src/net/nexttext/input/Keyboard.java,v 1.4 2004/08/03 15:53:50 dissent Exp $";

	/**
	 * Class constructor
	 *
	 * @param	component	the component the keyboard is added to
	 */
	public KeyboardDefault(Component component) {
		component.addKeyListener(this);
	}
	
	// Key listener
	public void keyPressed(KeyEvent event) {
		addEvent(new KeyboardEvent(event));
	}
	public void keyReleased(KeyEvent event) {
		addEvent(new KeyboardEvent(event));
	}
	public void keyTyped(KeyEvent event) {
		addEvent(new KeyboardEvent(event));
	}
}
