//
// Copyright 2004 Jason Lewis
//

package net.nexttext.input;

import java.awt.event.MouseEvent;

/**
 * An event generated by the mouse.
 *
 * <p>This is a wrapper around the {@link MouseEvent} class.  All IDs returned 
 * by the functions of this class are the same IDs used in the
 * Java {@link MouseEvent} class.</p>
 */

public class MouseInputEvent extends InputEvent {

    static final String REVISION = "$CVSHeader: obx/NextText/src/net/nexttext/input/MouseNTEvent.java,v 1.4 2004/07/06 14:46:37 brunon Exp $";

	// The mouse event
	MouseEvent event;
	
	/**
	 * Class constructor
	 *
	 * @param	event	the generated event
	 */
	 public MouseInputEvent(MouseEvent event) {
	 	this.event = event;
	 }
	 
	 /**
	  * Gets the type of event
	  *
	  * @return		the type of event
	  */
	 public int getType() {
	 	return event.getID();
	 }
	 
	 /**
	  * Gets the button attached to the event
	  *
	  * @return		the button id
	  */
	 public int getButton() {
	 	return event.getButton();
	 }
	 
	 /**
	  * Gets the x position of the mouse at the event
	  *
	  * @return		the x position
	  */	 
	 public int getX() {
	 	return event.getX();
	 }
	 
	 /**
	  * Gets the y position of the mouse at the event
	  *
	  * @return		the y position
	  */	 
	 public int getY() {
	 	return event.getY();
	 }
}
