//
// Copyright 2004 Jason Lewis
//

package net.nexttext.input;

import java.io.Serializable;

/**
 * An input event generated by an external source. 
 */

public abstract class InputEvent implements Serializable {

    static final String REVISION = "$CVSHeader: obx/NextText/src/net/nexttext/input/InputEvent.java,v 1.1 2004/07/26 13:58:35 dissent Exp $";

}
